version: "3.8"

services:
  mysqldb:
    image: 'mysql:8.0.31'
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel21
      - MYSQL_DATABASE=account-control
    ports:
      - '3307:3306'
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: 'autoservice'
    build: .
    env_file: ./.env
    ports:
      - '6868:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/account-control?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "12Marvel21",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'